# Generated by Django 4.2.7 on 2023-12-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_temaforo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temaforo',
            name='mensaje',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
