# Generated by Django 4.2.7 on 2023-12-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='mensaje',
            field=models.TextField(default=''),
        ),
    ]
