# Generated by Django 4.2.7 on 2023-12-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tema_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
